//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <KNSoft/Precomp4C/I18N/I18N.h>

enum
{
    Precomp4C_I18N_All_RectangleEditor,
    Precomp4C_I18N_All_Reset,
    Precomp4C_I18N_All_OK,
    Precomp4C_I18N_All_Left,
    Precomp4C_I18N_All_Top,
    Precomp4C_I18N_All_Right,
    Precomp4C_I18N_All_Bottom,
    Precomp4C_I18N_All_Width,
    Precomp4C_I18N_All_Height,
};

EXTERN_C PRECOMP4C_I18N_TABLE Precomp4C_I18N_Table_All;
