//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#include <KNSoft/Precomp4C/I18N/I18N.h>

PRECOMP4C_I18N_TABLE Precomp4C_I18N_Table_All = {
    (void*)0,
    0,
    2,
    {
        &(PRECOMP4C_I18N_LOCALE)
        {
            0xFFFF,
            L"en",
            {
                L"Rectangle Editor",
                L"Reset",
                L"OK",
                L"Left",
                L"Top",
                L"Right",
                L"Bottom",
                L"Width",
                L"Height",
            }
        },
        &(PRECOMP4C_I18N_LOCALE)
        {
            0xFFFF,
            L"zh-Hans",
            {
                L"矩形编辑器",
                L"重置",
                L"确定",
                L"左",
                L"上",
                L"右",
                L"下",
                L"宽",
                L"高",
            }
        },
    }
};

