//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <KNSoft/Precomp4C/Res2C/Res2C.h>

EXTERN_C unsigned char Precomp4C_Res2C_Resource_O5_O101_1024[384];
EXTERN_C unsigned char Precomp4C_Res2C_Resource_SAFX_DIALOG_LAYOUT_O101_1024[2];
EXTERN_C PRECOMP4C_RES2C_ENTRY Precomp4C_Res2C_Resource[2];